# Generated by Django 5.0.7 on 2025-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bed_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.IntegerField(unique=True),
        ),
    ]
