# Generated by Django 5.0.7 on 2025-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.IntegerField(),
        ),
    ]
